security:
  jwt:
    accessToken:
        secret: accessToken           #${ACCESS_TOKEN}
        expiration: 1800000
    refreshToken:
        secret: refreshToken          #${REFRESH_TOKEN}
        expiration: 1800000